email manager
lalaalal/AirportInfo pull request #12
Opened 2022-11-09 10:26 UTC by ShinHeeYoun

2022-11-10 06:33 UTC, ShinHeeYoun commented
이메일 기능 완성해서 pull request 합니다

2022-11-11 06:43 UTC, lalaalal requested changes
![image](https://user-images.githubusercontent.com/39375299/201279459-a90e584e-05ce-432c-8bad-392db4e4b8a0.png)

 클래스 선언 위에 이런 형식으로 author이름 바꿔서 추가해주세요!
그리고 파일 인코딩을 UTF8로 바꿔주셨으면 좋겠습니당

2022-11-12 05:40 UTC, ShinHeeYoun commented
author 수정 완료 + 추가 주석문

2022-11-12 09:35 UTC, lalaalal approved these changes
좋아요!

2022-11-12 09:36 UTC, merged